### PR TITLE
increased responsiveness of manage workflow

### LINKED ISSUE #5: Table from manage workflow section of Krini is not showing responsive behavior
**Issue**
Table from manage workflow section of Krini is not showing responsive behavior (the table is overflowing outside the container div)

**Steps to reproduce the behavior:**
1. Go to '[Krini > Manage Workflows](https://krini.rahtiapp.fi/manage)'
2. Use devtools to observe the  page in different devices

**Screenshots**
localhost_3000_manage(iPhone SE)

**Smartphone:**
 - Device: All devices under width 573px

### PR DESCRIPTION
**Pull request by tanya17-05**
**Details**
Makes table at manage workflow responsive to mobile devices by adding horizontal scroll to it.

Closes #5 

**Before**
localhost_3000_manage(iPhone SE)

**After**
localhost_3000_(iPhone SE)

### CODE REVIEW

**Review by uniqueg — APPROVED** [review]

**Comment by uniqueg** [comment]
Looks good to me - thanks @tanya17-05 :)

@git-anurag-hub: if it's fine with you, please merge

File: src/components/ManageWorkflows.js [hunk 1]
```diff
@@ -132,31 +132,33 @@ const ManageWorkflows = ({ isLoggedIn, showToast }) => {
...
-                Run Status
-              </th>
-            </tr>
-          </thead>
-          {renderRuns()}
-        </table>
+        <div className="overflow-x-auto">
+          <table className="table-auto min-w-full">
+            <thead className="bg-white">
+              <tr>
```
Comment (git-anurag-hub) [inline src/components/ManageWorkflows.js:138]: Hey Tanya, Thanks for the review. You can remove the s.no. field in the mobile view as it takes the extra space & doesn't provide any important information.

**Review by git-anurag-hub — CHANGES_REQUESTED** [review]

**Review by git-anurag-hub — APPROVED** [review]
